config/routes.rb
SimplePm::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  match "signup", to: "users#new"
  match "signin", to: "sessions#new"
  match "signout", to: "sessions#destroy", via: :delete

  root to: 'static_pages#home'
  match '/home',to: "static_pages#home"
  match '/about',   to: 'static_pages#about'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  validates :name, presence: true, length:  { maximum:  50 } 

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  validates :password, presence: true, length:  { minimum:  6 } 
  validates :password_confirmation, presence: true

  private 
  def create_remember_token
    self.remember_token=SecureRandom.urlsafe_base64
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # def create
  #     user = User.find_by_email(params[:session][:email])
  #     if user && user.authenticate(params[:session][:password])
  #       # success then we need to display the profile page
  #     else
  #       # not quite right we need to render the sign in page again
  #        flash[:error] = "Invalid: forget it it buddy!"
  #       render 'new'
  #     end
  #   end
  #   def destroy
  #   end
  #   
  def new
  end

   def create
     user = User.find_by_email(params[:session][:email])
     if user && user.authenticate(params[:session][:password])
       # Sign the user in and redirect to the user's show page.
       sign_in user
       redirect_back_or user
       
     else
       flash.now[:error] = 'Invalid email/password combination' # Not quite right!
       render 'new'
     end
   end

   def destroy
     sign_out
     redirect_to root_path
   end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update]
  before_filter :correct_user,   only: [:edit, :update]
  def new
    @user=User.new
  end
  def show
    @user=User.find(params[:id])
  end
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      # debugger
      render 'new'
    end
  end
  def edit
    @user=User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      # handle a successful update here
      flash[:success]="Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in." 
    end
  end
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_title)
  base_title="Simple PM"
  if page_title.empty?
    base_title
  else
    "#{base_title} | #{page_title}"
  end
end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token]=user.remember_token
    self.current_user=user
  end
  # this sets the current user
  def current_user=(user)
    @current_user = user
  end  
  # this gets the current user
  def current_user
    # @current_user ||= User.find_by_remember_token(cookies[:remember_token])
    @current_user = @current_user || User.find_by_remember_token(cookies[:remember_token])
  end
  def current_user?(user)
    user == current_user
  end
  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
  
  def redirect_back_or(default)
     redirect_to(session[:return_to] || default)
     session.delete(:return_to)
   end
   
  def store_location
    session[:return_to] = request.fullpath
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container-fluid">

			<a class="brand" href="/">I Saw Who</a>
			<% if signed_in? %>    
			<div class="btn-group pull-right">

				<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
					<i class="icon-user"></i> <%= current_user.name %>
					<span class="caret"></span>
				</a>
				<ul class="dropdown-menu">
					<li>
						<%= link_to "Profile", user_path(current_user) %>
					</li>
						<li>
							<%= link_to "Settings", edit_user_path(current_user) %>
						</li>
						<%= link_to "Sign out", signout_path, method: "delete" %>
					</li>
				</ul>
			</div>
			<% else %>
			<div class="btn-group pull-right">
<%= link_to "Sign in", signin_path, class: "btn" %>
				
			</div>
			<% end %>
			<div class="nav-collapse">
				<ul class="nav">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "About", about_path %></li>
				</ul>
			</div><!--/.nav-collapse -->
		</div>
	</div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
<%= render 'layouts/header' %>
  <body>
  
    <div class="container">
		<% flash.each do |key, value| %>
		        <div class="alert alert-<%= key %>"><%= value %></div>
		      <% end %>
      <%= yield %>
      
        <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title,"About") %>
<h1>About Us</h1>
<h2>
  The <a href="http://stokes.net.au/">Start of Raifes new business on Rails</a>
  the longest journey starts with a single step.
</h2>

app/views/static_pages/home.html.erb
<% provide(:title,"Home") %>


 

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li class="active"><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li class="nav-header">Sidebar</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li class="nav-header">Sidebar</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
         	<div class="center hero-unit">
			  <h1>Welcome to I Saw Who</h1>

			  <h2>
			    This is the start of Raife's business.
			  </h2>

			  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
			</div>
          <div class="row-fluid">
            <div class="span6">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="span6">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
                      </div><!--/row-->

     
 
     </div><!--/span-->
      </div><!--/row-->

      

    

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
<%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
<%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title,  @user.name) %>



<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
     <h1><%= @user.name %></h1>
    </div>
    <div class="span10">
      <!--Body content-->
    </div>
  </div>
</div>